### PR TITLE
Improve GameVersionPoint handling

### LINKED ISSUE #59: It's impossible to get the version if it requires several method calls
To get the version in Desperados III you need to call something like `MiVersion.Version.ToFullString()` where `Version` is a getter. As far as I can tell the parser always sees `MiVersion.Version` as a type and tries to call the `ToFullString` method on it but since `MiVersion.Version` is not actually I type it fails.

I would be up to implement a fix but I wanted to ask first what you think the best solution is. My two ideas would be to either check every combination if one of them is a getter or introduce some special syntax to separate the type from the calls, like maybe `MiVersion::Version.ToFullString` similar to how you get a method in Java. Although the `:` would clash with the `:After` so maybe something else would be better, maybe `$` or `@`. On the other hand, since for the version the `:After` modifiers don't make sense anyways it could be used anyways and be separate from the code that parses the actual entry points. And of course, the old method still has to work in any case.

Besides that, quick question while I'm at it: The guide for adding a new game says that the starting point should be as early as possible. Is there a reason to have it really early (like even before the main menu) besides maybe that mods could then modify very early code?

And another thing, maybe it would be a good idea to close issues after they are solved? Otherwise, it gets a bit hard to see the ones that are actually still open.

### PR DESCRIPTION
**Pull request by benediktwerner**
As discussed in #59.

New behavior:

The `GameVersionPoint` can now contain arbitrarily many method calls, and field and property accesses after the initial type and static call or access. Only method calls without arguments are supported. Calls can optionally end with `()` but for backward compatibility, the parentheses can also be left out. 

So `MiVersion.Version.ToFullString()` and `MiVersion.Version.ToFullString` are equivalent.

Since I don't have the right Unity DLLs I couldn't test it yet but I checked it carefully and I'm fairly certain that it should work correctly.

When you publish this change it would be great if you could add `MiVersion.Version.ToFullString()` as the `GameVersionPoint` for Desperados III as well.

Closes #59

### CODE REVIEW

**Comment by newman55** [comment]
Need to add support for namespace. For example, the Pathfinder game uses it.

**Comment by benediktwerner** [comment]
Did you try it? Namespaces should work unless there is a bug I'm not seeing.

[Here](https://github.com/newman55/unity-mod-manager/pull/60/files#diff-c2f46560430c870369e564f582532985R1245), it finds the longest prefix that is a valid class which should work with namespaces and also nested classes.

**Comment by newman55** [comment]
I got error for <GameVersionPoint>[Assembly-CSharp.dll]Kingmaker.GameVersion.GetVersion</GameVersionPoint>
```
[Manager] Start parsing game version.
[Manager] [Error] No class found at 'Kingmaker..GameVersion.GetVersion'
[Manager] Parsing mods.
```

**Comment by newman55** [comment]
I removed the extra dot and everything seems to be working. 
Good job.

**Comment by benediktwerner** [comment]
Ah, yeah, I forgot about the first dot. Thanks.

**Pull request merged**
