### PR TITLE
Your code call UnityModManagerNet, but where is it ?

### PR DESCRIPTION
**Pull request by Nemesis666first**
Hi,

I dont understand how your code can call UnityModManagerNet, but I see no reference to UnityModManagerNet.dll in your files, can you help me please ?

### CODE REVIEW

**Comment by newman55** [comment]
You need only UnityModManager.dll

**Comment by Nemesis666first** [comment]
When I load UnityModManager.dll, and I call "using UnityModManagerNet;", "UnityModManagerNet" appear in red :o , do you have an idea why :o ?

**Comment by newman55** [comment]
[Guide](https://wiki.nexusmods.com/index.php/How_to_create_mod_for_unity_game)

**Comment by Nemesis666first** [comment]
I successfully found "UnityModManagerNet" inside "UnityModManager.dll", but I still have the same issue, thank you for your time and your help ;) .

**Comment by newman55** [comment]
I don't even have any idea why your compiler doesn't see UnityModManagerNet.

**Pull request closed without merging**
