### PR TITLE
Update project files to modern format

### PR DESCRIPTION
**Pull request by PhilPJL**
UnityModManager

- new project file format 
- targets .NET 3.5
- references dnlib and HarmonyX as packagerefs (Nuget)

Updater

- new project file format
- multi-targeted to .NET 3.5 and .NET 4.7.2.  There are separate build outputs for each platform.
- sets ServicePointManager.SecurityProtocol correctly dependent on platform
- deleted app.config.  This gets generated automatically on build.

UMM app
- new project file format
- multi-targeted to .NET 3.5 and .NET 4.7.2 There are separate build outputs for each platform.
- deleted app.config.  This gets generated automatically on build.
- dnlib and HarmonyX get pulled in from project ref on UMM
- Ionic and Newtonsoft are now packagerefs
- Updater is now a project ref so that Updater project outputs get automatically copied to UMM app outputs.
- required lib assemblies are now linked files with 'copy always'
- updated libraryFiles to include Harmony 2.4 dependencies

Remove .NET 3.5 build configuration.

Tested that my mods are installed, uninstalled and updated, and work in game (Solasta).

I appreciate that you would need to do further testing before accepting this, so if you don't have time never mind.
If you do merge this code, then I would recommend deleting all bin and obj folders and rebuilding otherwise VS gets confused.

### CODE REVIEW

**Comment by newman55** [comment]
All libraries must be net 3.5 and I don't want to depend on HarmonyX unnecessarily, this is an external project for bepinex. I use Harmony Proxy so any discrepancy with the original could break compatibility.

**Comment by PhilPJL** [comment]
I didn't know there was a Harmony proxy.  I'll put that back.   HarmonyX works though.
Regarding the .net versions, I wasn't sure if I had got things right, but after my changes:
UMM is .net 3.5
UMM app + loader is .net 3.5 or .net 4.7.2 (which can easily be changed to .net 4.5.x.)  Note that .net 4.5 is no longer supported so you should at least update to 452.

**Comment by newman55** [comment]
dnlib, mono.cecil, and harmony is 4.x

**Comment by newman55** [comment]
Ok, this is my mistake because I compiled in 4.x. 3.5 refused to start for me.

**Comment by PhilPJL** [comment]
Yes dnlib is compatible with 3.5 or 4.5

image

**Comment by PhilPJL** [comment]
I'll fix the harmony bit later.  Busy atm.

**Comment by PhilPJL** [comment]
Restored harmony proxy.
Note that I removed system.xml because it didn't seem necessary.  If that's required I can add it back.

**Comment by newman55** [comment]
It is needed because it is used by unity in older versions and conflicts with the native one.

**Comment by PhilPJL** [comment]
Added back

**Comment by newman55** [comment]
UnityModManagerApp.exe on net 3.5 dont work for me.

**Comment by PhilPJL** [comment]
There's an issue with .NET 3.5.  
https://stackoverflow.com/questions/5942537/splitcontainer-isupportinitialize-issue-vs2010-targeting-net-3-5
You can debug .NET 3.5 or 4.7.2 with
image

**Comment by newman55** [comment]
Still not compatible with net35?

**Comment by PhilPJL** [comment]
That depends what you mean by not compatible.  I've merged your latest updates and the solution builds and creates .net35 and .net472 outputs which both work.   .Net35 version works without error now.

However, the issue with ISupportInitialize still exists and is confirmed by MS https://github.com/dotnet/winforms/issues/4780#issuecomment-818391325.  This is a problem for you anyway.

Also I was trying to change the .net35 output assembly name and discovered an issue with conditional PropertyGroup
https://github.com/dotnet/project-system/issues/7120#issuecomment-818987856.

I guess I may have to close this for now.

**Comment by newman55** [comment]
Yes, I would not want to mess around with ISupportInitialize. 
Good job anyway.

**Comment by PhilPJL** [comment]
Closing for now until MS sort a couple of bugs (could be waiting a long time though).

**Comment by PhilPJL** [comment]
Microsoft's response: https://github.com/dotnet/winforms/issues/4780

**Pull request closed without merging**
